productName: wb-electron
appId: wbingcs
directories:
  output: dist-electron
copyright: Copyright © 2019 wbingcs
dmg:
  contents:
    - x: 410
      'y': 150
      type: link
      path: /Applications
    - x: 130
      y: 150
      type: file